### ISSUE TITLE
Нет геттеров для price и feedId

### ISSUE THREAD

**Issue by 4selin** [yandex-market/beru-php-partner#3]
Цитата из [Вики](https://github.com/yandex-market/beru-php-partner/wiki/%D0%9C%D0%B5%D1%82%D0%BE%D0%B4%D1%8B-%D0%B4%D0%BB%D1%8F-%D0%BC%D0%BE%D0%B4%D0%B5%D0%BB%D0%B8-%C2%AB%D0%92%D0%B8%D1%82%D1%80%D0%B8%D0%BD%D0%B0-+-%D0%B4%D0%BE%D1%81%D1%82%D0%B0%D0%B2%D0%BA%D0%B0%C2%BB#%D0%9E%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B0-%D0%B7%D0%B0%D0%BA%D0%B0%D0%B7%D0%BE%D0%B2)

> // Получаем заказ
> $order = $orderProcessingBeruClient->acceptOrder($request);
> 
> // Печатаем информацию о товарах в корзине
> $items = $order->getItems();
> foreach ($items as $item) {
>    print_r($item);
> }

$item не имеет геттеров для price и feedId. На это есть причины или нет? 

Если нет, то
feedId нужен для обработки /cart на стороне магазина
price для /order/accept
Рассмотрите возможность добавления геттеров для price и feedId, пожалуйста.

**Comment by VitaliaSmaglenko** [comment]
@4selin  
Для метода $orderProcessingBeruClient->acceptOrder($request) есть геттеры для price и feedId
Чтобы получить price и feedId: 
// Получаем заказ
$order = $orderProcessingBeruClient->acceptOrder($request);
// Печатаем информацию о товарах в корзине
$items = $order->getItems();
foreach ($items as $item) {
    echo 'FeedId: ' . $item->getFeedId();
    echo 'Price: ' . $item->getPrice();
}
