### ISSUE TITLE
у StocksClient отсутствует метод getWarehouseId()

### ISSUE THREAD

**Issue by 4selin** [yandex-market/beru-php-partner#5]
Доброго времени!

1. в [вики ](https://github.com/yandex-market/beru-php-partner/wiki/%D0%9C%D0%B5%D1%82%D0%BE%D0%B4%D1%8B-%D0%B4%D0%BB%D1%8F-%D0%BC%D0%BE%D0%B4%D0%B5%D0%BB%D0%B8-%C2%AB%D0%92%D0%B8%D1%82%D1%80%D0%B8%D0%BD%D0%B0-+-%D0%B4%D0%BE%D1%81%D1%82%D0%B0%D0%B2%D0%BA%D0%B0%C2%BB#%D0%9E%D1%81%D1%82%D0%B0%D1%82%D0%BA%D0%B8-%D1%82%D0%BE%D0%B2%D0%B0%D1%80%D0%BE%D0%B2) в разделе "Остатки товаров" ошибка:

написано
`$stocksClient = new \Yandex\Beru\Partner\Clients\ShipmentsClient($clientId, $token);`

а должно быть **StocksClient**
`$stocksClient = new \Yandex\Beru\Partner\Clients\StocksClient($clientId, $token);`

**Comment by VitaliaSmaglenko** [comment]
@4selin  исправлено на StocksClient
